### ISSUE TITLE
Why can a 1 resource be used Many times?

### ISSUE THREAD

**Issue by qcfu-bu** [LightAndLight/qtt#2]
https://github.com/LightAndLight/qtt/blob/08a3ee8361178ad13bba659af4751b55c91081b7/src/Typecheck.hs#L535

This line of code indicates that a 1 (linear) resource can be used Many times. From my understanding of Qtt, this shouldn’t be allowed. Am I missing something here?

**Comment by LightAndLight** [comment]
In this code, `u` is "the context in which we're doing inference", and `u'` is "the variable's remaining usages".

line 528: If we're doing inference in a `Zero` context (i.e. a type signature), then we don't consume the variable (leave its usage unchanged)

lines 529 - 532: If we're doing inference in a `One` context, then we need to consume the variable. If the variable has `Zero` usages left, then it's an error. If it has `One` usage left, then we consume it, leaving it with `Zero` usages. If it has `Many` usages left then we leave its usage unchanged because `Many` is inexhaustible.

lines 533 - 536: Same as the `One` context.

Does that make sense?

I'm pretty sure this logic is correct, but if you keep reading you're bound to find a mistake somewhere. Most obviously, I'm using a [borked semiring definition](https://github.com/LightAndLight/qtt/blob/08a3ee8361178ad13bba659af4751b55c91081b7/src/Syntax.hs#L52) because I misunderstood some parts of the paper. So take everything you read with a grain of salt :)

**Comment by qcfu-bu** [comment]
My confusion was with these two lines specifically.

https://github.com/LightAndLight/qtt/blob/08a3ee8361178ad13bba659af4751b55c91081b7/src/Typecheck.hs#L534-L535

Because this seems like it's trying to get Many uses out of a One variable.

Edit: That semi-ring definition definitely looks fishy.

**Comment by LightAndLight** [comment]
I might have a go at fixing it up later this week. If I do then I'll ping you here.

I'm pretty interested in coming up with a counterexample that demonstrates this is broken.

**Comment by qcfu-bu** [comment]
The commented out semi ring seems correct to me, did it not work out?

This gist might interest you, it has been very helpful to me so far.
https://gist.github.com/gabriel-barrett/0de85a606b64886052854422fb05ce0c

**Comment by LightAndLight** [comment]
Thanks.

> The commented out semi ring seems correct to me, did it not work out?

From what I remember of my at-the-time-muddled thinking, I was mucking with the semiring because I was trying to 'get around' the `Gamma |- x :{0,1} T` restriction laid out in Atkey's paper. I'd have to dive back in to the code to figure out exactly what my misunderstanding was.

**Comment by LightAndLight** [comment]
@qcfu-bu, I've fixed things to my best ability in `master`. Let me know what you think. And feel free to contact me if you have further questions.
